### ISSUE TITLE
Add sudo to base image

### ISSUE THREAD

**Issue by mszoek** [mszoek/helium#26]

**Comment by BodilessSleeper** [comment]
Wouldn't it be a better idea to use doas instead?
It's easier to configure, takes up less space and it's just simpler and therefore more reliable in general (also a program developed by BSD guys, for BSD in mind)

**Comment by mszoek** [comment]
Possibly! I wasn't aware of `doas` so thanks for pointing it out. It looks like a good alternative for most uses of `sudo`. However, given the design goals of the project, I think we still need `/usr/bin/sudo` to follow what macOS has.

**Comment by BodilessSleeper** [comment]
Oh well, you could make doas a symlink to /usr/bin/sudo if you just care about people typing in sudo and getting a command not found error, but I can see you wanting sudo for replicating the macOS experience as close as possible

**Comment by mszoek** [comment]
A simple wrapper might be viable. I suspect most users only use `sudo <cmd>` or `sudo -u` so most CLI options could be ignored.

**Comment by BodilessSleeper** [comment]
Yeah, I wanted to say most users only run sudo command but I didn't want to sound aggresive, and if you keep that in mind there is no need for a wrapper since doas gives you the same functionality for both sudo command and sudo -u command, with the exception of giving you one try instead of 3 to type in your password correctly, so I don't even think a wrapper is necessary, just linking the doas binary to /usr/bin/sudo will work out of the box and if it didn't say `doas (x@y) password:` most people wouldn't even realise it wasn't sudo in the first place
