### ISSUE TITLE
Building on linux

### ISSUE THREAD

**Issue by marchellodev** [mszoek/helium#32]
Hey, is it possible to build the iso on linux?

**Comment by mszoek** [comment]
Hey :)

It is technically *possible* but would be a big effort. I specifically targeted FreeBSD for [Reasons](https://github.com/mszoek/helium#why-bsd-instead-of-linux) so that would all have to be replaced:
* The Makefiles are written for BSD make, as are the makefile includes for building app bundles and frameworks.
* The LLVM/Clang toolchain that supports linking frameworks is patched & built from the FreeBSD source tree.
* The frameworks themselves have platform-specific bits which should work on Linux but ... *shrug* 
* Many paths would probably be wrong for the LFS
* Parts of the system are built out of the FreeBSD `ports` collection
