### ISSUE TITLE
How can I contribute

### ISSUE THREAD

**Issue by tyu1996** [mszoek/helium#38]
I am interested on this project, but never had participate in larger project like this before. 

Code wise, so far I can only help on the Python part. I am not sure where to start, and how to setup the development environment for this project. 

Would like to ask for a simple guide on this, thank you.

**Comment by mszoek** [comment]
Hey! :) I would be happy to have some help!

The dev environment is Helium itself now, so download the M1 image from Releases and install it in a VM or spare PC. It is still pretty minimal but you can install your favorite editor or IDE from Packages, _or_ you can set up a shared filesystem like NFS or shared virtual machine folder mounted on your normal desktop. SSH is enabled too, and Python 3.7 is installed.

For Python to be really useful, it needs to be hooked into the Cocoa frameworks so that Python apps can call all those routines like drawing windows, setting the menu bar, locating bundle resources, etc. Have you ever wrapped Python around C libraries? Something like this may be a good starting point: https://opensource.apple.com/source/pyobjc/pyobjc-56.40.4/

If you want something simpler to start with, how about writing the [`open`]https://ss64.com/osx/open.html) or [`defaults`](https://ss64.com/osx/defaults.html) command? We'll have to fake the back end a bit but should be able to write these. One big challenge is going to be adapting different config backends (e.g. `dconf`, KDE config files, XDG configs) to use the Preferences plist files. (I think this will ultimately be easier than trying to synchronize multiple config sources whenever settings are changed.)

**Comment by tyu1996** [comment]
Never had done system programming nor having MacOS/BSD experience before, but I believe here is the best opportunity for me to experience it when the project is still smaller.

Sure, I might look into something small first, perhaps starts with CLI tools as you mentioned. Thanks!

**Comment by mszoek** [comment]
Awesome! Let me know if you have any questions 😀
